from Tree import *
tree= BST()
tree.insert(50)
print(tree.find_max())
tree.insert(25)
print(tree.find_max())
tree.insert(75)
tree.insert(30)
tree.insert(60)
tree.root.display()
print(tree.find_max())
print(50 in tree)
print(37 in tree)
tree.insert(77)
tree.insert(24)
tree.insert(90)
print()
print(tree.find_max())
print()
tree.root.display()
tree.traverse_preorder()
print()
tree.traverse_postorder()
print()
tree.traverse_inorder()
print(len(tree))
print(helpright(tree.root))
print(tree.remove(90))
print(tree.count)
tree.root.display()
print(tree.remove(75))
print(tree.count)

tree.root.display()
print(tree.remove(50))
print(tree.count)
tree.root.display()
print(tree.remove(24))
tree.root.display()
print(tree.remove(25))
print(tree.count)
tree.root.display()
tree.insert(79)
tree.insert(61)
tree.insert(63)
tree.root.display()
print(tree.remove(60))
tree.root.display()
tree.insert(78)
tree.insert(100)
tree.insert(65)
tree.insert(62)
tree.root.display()
tree.remove(65)
print(tree.count)
tree.root.display()
tree.remove(77)
tree.root.display()
print(tree.remove(111))
tree.insert(50)
tree.insert(65)
tree.insert(55)
tree.insert(57)
tree.root.display()
tree.remove(50)
print(tree.count)
tree.root.display()
tree.insert(51)
tree.insert(53)
tree.root.display()
tree.remove(51)
print(tree.count)
tree.root.display()
tree.remove(61)
print(tree.count)
tree.root.display()
tree.remove(78)
print(tree.count)
tree.root.display()
tree.remove(55)
tree.root.display()
tree.remove(53)
tree.root.display()
tree.remove(65)
print(tree.count)
tree.root.display()
tree.remove(62)
tree.root.display()
tree.remove(79)
print(tree.count)
tree.root.display()
tree.remove(63)
tree.root.display()
tree.remove(100)
print(tree.count)
tree.root.display()
tree.remove(30)
tree.remove(57)
print(len(tree))







