from CircularlyLinkedList import *
names = CircularlyLinkedList()
print('Names should be empty, True: ',names.is_empty())
names.add('Tyler')
print('Added Tyler')
print('Head.next should be Tyler:',names.head.next)
print('Last.next should be Tyler:',names.last.next)
print()
print('Added Colleen')
names.add('Colleen')
print('Last.next should be Colleen:',names.last.next)
print('Names in order:')
for x in names:
    print(x)
print('\nAppended David and Dan')
names.append('David')
names.append('Dan')
print('Size should be 4:',names.size())
print('Names in order:')
for x in names:
    print(x)
# names.remove("Band")  ###This will result in an error message
print()
print('Popping last index should be Dan:',names.pop())
print('Size of names should be 3:',names.size())
print('Names in order:')
for x in names:
    print(x)
print()
names.add('Hally')
print('Added Hally and popped at index 0, should be Hally:',names.pop(0))
print('\nNames in order:')
for x in names:
    print(x)
print()
print('Popping at index 1, should be Tyler:',names.pop(1))
print('Names in order:')
for x in names:
    print(x)
print('Last should be David:',names.last)
print('Last.next should be Colleen:',names.last.next)
print('Names is not empty, False:',names.is_empty())
print()
names.append('Tyler')
names.remove('Tyler')
print('Appended and Removed Tyler, Names in order:')
for x in names:
    print(x)
print()
print('Last should be David:',names.last)
print('Last.next should be Colleen:',names.last.next)
names.add('Tyler')
names.remove('Tyler')
print('\nAdded and Removed Tyler, Names in order:')
for x in names:
    print(x)
print()
print('Last should be David:',names.last)
print('Last.next should be Colleen:',names.last.next)
names.append('Katie')
names.remove('David')
print('\nAppended katie and Removed David, Names in order:')
for x in names:
    print(x)
print()
print('Last should be Katie:',names.last)
print('Last.next should be Colleen:',names.last.next)
names.append('Pop')
names.append('Brian')
names.remove('Katie')
print('\nAppended Pop and Brian and removed Katie, Names in order:')
for x in names:
    print(x)
print()
print('Last should be Brian:',names.last)
print('Last.next should be Colleen:',names.last.next)
print('Popped at index 1, should be Pop:',names.pop(1))
print('Names in order:')
for x in names:
    print(x)
print()
print('Last should be Brian:',names.last)
print('Last.next should be Colleen:',names.last.next)
print('Popped at index 0, should be colleen:',names.pop(0))
print('Names should not be empty, False:',names.is_empty())
print('Names in order:')
for x in names:
    print(x)
print()
print('Head should be Brian:',names.head)
print('Last should be Brian:',names.last)
print('Head.next should be Brian:',names.head.next)
print('Last.next should be Brian:', names.last.next)
print('\nBrian was removed')
names.remove('Brian')
print('Names should be empty, True:',names.is_empty())
print('Names size should be 0:',names.size())
print('\nAdded Pop, Tyler, Greg, and Tyler then removed Tyler')
names.add('Pop')
names.add('Tyler')
names.add('Greg')
names.add('Tyler')
names.remove('Tyler')
print('Names in order: Greg, Tyler, Pop')
for x in names:
    print(x)



